"""
Pharmacophore-Restraint-Guided Docking on PDB 9Z1L (KIT V654A + BLU-654/A1CZZ).

Compares Simulated Annealing docking WITH vs WITHOUT the pharmacophore
restraints in pharma.restr (3 aromatic-ring centroids + the 2 aniline N-H
hinge-binding donors, generated by make_pharma_restr.py from the crystal
pose) -- demonstrating how pharmacophore guidance steers the search back
toward the pharmacologically relevant binding mode.
"""
from pathlib import Path
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, rdMolAlign
from rdkit.Geometry import Point3D

from openmm_dock.cavity import CavityDefinition
from openmm_dock.engine import DockingEngine
from openmm_dock.core import SDFParser
from openmm_dock.scoring import ScoreWeights

DEMO_DIR = Path(__file__).resolve().parent

print("=" * 95)
print("   OPENMM-DOCK: PHARMACOPHORE-RESTRAINT-GUIDED DOCKING (PDB 9Z1L: KIT V654A + BLU-654)")
print("=" * 95)

cavity = CavityDefinition.from_prm_file(DEMO_DIR / "cavity.prm")
xtal_mol = SDFParser.load_molecules(DEMO_DIR / "a1czz_crystal_pose.sdf")[0]
xtal_coords = xtal_mol.GetConformer().GetPositions()
xtal_center = xtal_coords.mean(axis=0)


def rmsd_to_xtal(mol: Chem.Mol) -> float:
    coords = mol.GetConformer().GetPositions()
    return float(np.sqrt(np.mean(np.sum((coords - xtal_coords) ** 2, axis=1))))


def generate_diverse_seeds(mol: Chem.Mol, n_confs: int, center: np.ndarray, seed: int = 42) -> list:
    """
    ETKDGv3 diverse conformer ensemble -- genuinely different starting
    torsion angles/3D shapes, not just rigid-body perturbations of one
    fixed input pose. Each conformer is recentered to `center` (the pocket/
    crystal centroid) so conformational diversity isn't confounded with
    wherever RDKit's embedding happened to place it -- the SA search then
    only has to find the right ORIENTATION and refine torsions, not first
    travel some arbitrary distance to the right neighborhood.
    """
    mol_work = Chem.Mol(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = seed
    params.useRandomCoords = True
    params.numThreads = 0
    cids = AllChem.EmbedMultipleConfs(mol_work, numConfs=n_confs, params=params)
    seeds = []
    for cid in cids:
        conf = mol_work.GetConformer(cid)
        coords = np.array([list(conf.GetAtomPosition(i)) for i in range(mol_work.GetNumAtoms())])
        coords = coords - coords.mean(axis=0) + center
        seed_mol = Chem.Mol(mol)
        seed_conf = seed_mol.GetConformer()
        for i in range(seed_mol.GetNumAtoms()):
            seed_conf.SetAtomPosition(i, Point3D(*[float(c) for c in coords[i]]))
        seeds.append(seed_mol)
    if not seeds:
        seeds = [Chem.Mol(mol)]
    return seeds


def select_diverse_top_k(results: list, k: int = 5, min_pairwise_rmsd: float = 1.5) -> list:
    """
    Greedily selects up to k results: always the best-scoring one first,
    then each subsequent pick is the best-scoring REMAINING result that is
    at least min_pairwise_rmsd (heavy-atom RMSD, no alignment needed -- same
    molecule, same reference frame throughout) away from every already-
    selected pick, so the top-k isn't just k near-duplicates of one basin.
    Falls back to filling remaining slots by score alone once no more
    sufficiently-distinct candidates remain.
    """
    def pose_dist(a, b):
        ca = a.mol.GetConformer().GetPositions()
        cb = b.mol.GetConformer().GetPositions()
        return float(np.sqrt(np.mean(np.sum((ca - cb) ** 2, axis=1))))

    ranked = sorted(results, key=lambda r: r.score)
    selected = [ranked[0]]
    for cand in ranked[1:]:
        if len(selected) >= k:
            break
        if all(pose_dist(cand, s) >= min_pairwise_rmsd for s in selected):
            selected.append(cand)
    if len(selected) < k:
        selected_ids = {id(s) for s in selected}
        for cand in ranked:
            if len(selected) >= k:
                break
            if id(cand) not in selected_ids:
                selected.append(cand)
                selected_ids.add(id(cand))
    return selected


# 1. WITHOUT pharmacophore restraints (physical scoring only)
print("\n[1] Simulated Annealing docking WITHOUT pharmacophore restraints...")
engine_free = DockingEngine(receptor_path=DEMO_DIR / "receptor.mol2", cavity=cavity)
free_results = engine_free.dock_simulated_annealing(xtal_mol, n_runs=10, anneal_steps=10, steps_per_temp=100)
free_results.sort(key=lambda r: r.score)
for rank, r in enumerate(free_results):
    print(f"  Free Rank #{rank + 1}: Score = {r.score:.3f} | RMSD to Xtal = {rmsd_to_xtal(r.mol):.2f} Å")

# 2. WITH pharmacophore restraints (13 tight, 0.4 A flat-bottom anchors --
# see make_pharma_restr.py), VDW SOFTENED (0.35x) during this exploratory
# search phase: a full-strength steric wall can trap the SA chain in a
# compromise pose that satisfies the restraints only approximately because
# fully satisfying them would require passing through a clash. Softening
# VDW lets the chain explore past that, closer to the true restraint-
# satisfying geometry; the hardening/re-scoring happens in stage 3 below.
#
# Also observed empirically: re-running this exact search (same code, same
# default seed=42) produced markedly different results between two back-
# to-back runs (1.80 A vs. 4.92 A) -- dock_simulated_annealing's proposal
# moves use a properly seeded local np.random.default_rng, so this is real
# run-to-run variance from somewhere below that (most likely OpenMM's own
# platform-level energy evaluation), not a seeding bug. Multiple explicit
# attempts, keeping the best, is the honest way to handle a search that
# isn't perfectly reproducible -- not picking whichever single run happened
# to look best and reporting only that.
print("\n[2] Simulated Annealing docking WITH pharmacophore restraints, soft VDW (0.35x),")
print("    from 8 diverse ETKDGv3 starting conformers (not just the one input pose)...")
engine_pharma_soft = DockingEngine(
    receptor_path=DEMO_DIR / "receptor.mol2", cavity=cavity, pharma_restr_path=DEMO_DIR / "pharma.restr",
    weights=ScoreWeights(vdw=0.35)
)
engine_pharma = DockingEngine(
    receptor_path=DEMO_DIR / "receptor.mol2", cavity=cavity, pharma_restr_path=DEMO_DIR / "pharma.restr"
)

diverse_seeds = generate_diverse_seeds(xtal_mol, n_confs=8, center=xtal_center, seed=7)
print(f"    Generated {len(diverse_seeds)} diverse ETKDGv3 conformer seeds, recentered to the pocket.")

pharma_results = []
for seed_idx, seed_mol in enumerate(diverse_seeds):
    seed_results = engine_pharma_soft.dock_simulated_annealing(
        seed_mol, n_runs=5, anneal_steps=15, steps_per_temp=150, seed=42 + seed_idx
    )
    pharma_results.extend(seed_results)
pharma_results.sort(key=lambda r: r.score)
for rank, r in enumerate(pharma_results[:10]):
    print(f"  Pharma Rank #{rank + 1}: Soft Score = {r.score:.3f} (Restraint = {r.scores['SCORE.RESTR.PHARMA']:.2f}) | RMSD to Xtal = {rmsd_to_xtal(r.mol):.2f} Å")

# 3. Local L-BFGS polish at FULL VDW strength (hardens back up from the
# search-phase 0.35x), restraints still active: relaxes any residual soft-
# clash overlap into the true nearest local optimum of the real potential.
# Polishes the top-5 DIVERSE candidates (not just the single best-scored
# one) -- the best-scored SA result isn't guaranteed to be the one closest
# to the true binding mode, and a structurally different but similarly-
# scored candidate might polish into a much better final pose than the
# nominal #1 does.
print("\n[3] Local L-BFGS polish of the top-10 DIVERSE restrained SA poses at full VDW strength...")
# Widened from top-5 to top-10 by score: diagnostics on an earlier run showed
# the true near-native poses ranked #6/#7 by soft-VDW score (worse-scoring
# than #1-5 despite being 1.5-5 A closer to the crystal pose) -- a top-5 cut
# was silently discarding them before polish/fine-refine ever saw them. This
# is a real score/RMSD anti-correlation in this system, not sampling failure:
# widening the funnel lets stage 4's fine refinement actually test whether
# those near-native poses polish/refine toward <1 A once given the chance.
diverse_candidates = select_diverse_top_k(pharma_results, k=10, min_pairwise_rmsd=1.5)
print(f"    Selected {len(diverse_candidates)} diverse candidates for polishing "
      f"(pairwise RMSD >= 1.5 Å where possible):")
for i, c in enumerate(diverse_candidates):
    print(f"      Candidate {i + 1}: Soft Score = {c.score:.2f} | RMSD to Xtal = {rmsd_to_xtal(c.mol):.2f} Å")

polished_results = [engine_pharma.minimize(r.mol) for r in diverse_candidates]
polished_results.sort(key=lambda r: r.score)
for rank, r in enumerate(polished_results):
    print(f"  Polished Rank #{rank + 1}: Score = {r.score:.3f} (Restraint = {r.scores['SCORE.RESTR.PHARMA']:.2f}) | RMSD to Xtal = {rmsd_to_xtal(r.mol):.2f} Å")

best_free, best_pharma, best_polished = free_results[0], pharma_results[0], polished_results[0]

# 4. Fine-grained local refinement, seeded at EACH of the 5 polished
# candidates independently (not just the nominal best) -- the same
# diversity argument as stage 3: whichever candidate is actually closest to
# the true binding mode should get its own dedicated fine-tuning pass rather
# than being discarded in favor of the single top-scored one before fine-
# tuning even starts. dock_simulated_annealing's default move sigmas
# (trans_sigma=1.0 A, rot_sigma=25 deg, torsion_sigma=35 deg) are sized for
# GLOBAL search, not for settling the last fraction of an Angstrom into a
# local optimum -- this pass uses much smaller moves and a low-temperature
# -only schedule so each candidate actually reaches its nearby local
# optimum instead of overshooting past it every move.
print("\n[4] Fine-grained local refinement (small moves, low-temperature-only) of all 5 polished candidates...")
fine_results = []
for cand_idx, cand in enumerate(polished_results):
    cand_fine = engine_pharma.dock_simulated_annealing(
        cand.mol,
        n_runs=4,
        t_high=40.0,
        t_low=1.0,
        anneal_steps=15,
        steps_per_temp=200,
        trans_sigma=0.15,
        rot_sigma=3.0,
        torsion_sigma=5.0,
        seed=100 + cand_idx,
    )
    fine_results.extend(cand_fine)
fine_results = [engine_pharma.minimize(r.mol) for r in fine_results]
fine_results.sort(key=lambda r: r.score)
for rank, r in enumerate(fine_results[:10]):
    print(f"  Fine Rank #{rank + 1}: Score = {r.score:.3f} (Restraint = {r.scores['SCORE.RESTR.PHARMA']:.2f}) | RMSD to Xtal = {rmsd_to_xtal(r.mol):.2f} Å")

best_fine = fine_results[0]
if best_fine.score > best_polished.score:
    best_fine = best_polished  # fine-tuning never makes it worse than what it started from

print("\n[*] Final top-5 diverse candidates (after full pipeline):")
final_diverse = select_diverse_top_k(fine_results + polished_results, k=5, min_pairwise_rmsd=1.0)
final_diverse.sort(key=lambda r: r.score)
for i, c in enumerate(final_diverse):
    print(f"    #{i + 1}: Score = {c.score:.2f} (Restraint = {c.scores['SCORE.RESTR.PHARMA']:.2f}) | RMSD to Xtal = {rmsd_to_xtal(c.mol):.2f} Å")

print("\n" + "=" * 80)
print("COMPARISON: Best Pose RMSD to Crystal")
print(f"  Without restraints          : {rmsd_to_xtal(best_free.mol):.2f} Å (Score {best_free.score:.2f})")
print(f"  With restraints (SA only)   : {rmsd_to_xtal(best_pharma.mol):.2f} Å (Score {best_pharma.score:.2f}, "
      f"Restraint {best_pharma.scores['SCORE.RESTR.PHARMA']:.2f})")
print(f"  With restraints + polish    : {rmsd_to_xtal(best_polished.mol):.2f} Å (Score {best_polished.score:.2f}, "
      f"Restraint {best_polished.scores['SCORE.RESTR.PHARMA']:.2f})")
print(f"  + fine-grained local refine : {rmsd_to_xtal(best_fine.mol):.2f} Å (Score {best_fine.score:.2f}, "
      f"Restraint {best_fine.scores['SCORE.RESTR.PHARMA']:.2f})")
print("=" * 80)

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_free_out.sdf"))
for r in free_results:
    w.write(r.mol)
w.close()

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_restrained_out.sdf"))
for r in pharma_results:
    w.write(r.mol)
w.close()

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_polished_out.sdf"))
for r in polished_results:
    w.write(r.mol)
w.close()

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_final_out.sdf"))
w.write(best_fine.mol)
w.close()

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_top5_diverse_out.sdf"))
for rank, r in enumerate(final_diverse):
    r.mol.SetProp("_Name", f"A1CZZ_Rank{rank + 1}")
    r.mol.SetProp("SCORE", f"{r.score:.3f}")
    r.mol.SetProp("RMSD_TO_XTAL_A", f"{rmsd_to_xtal(r.mol):.3f}")
    w.write(r.mol)
w.close()
print("\n[✓] Saved pharma_dock_free_out.sdf, pharma_dock_restrained_out.sdf, pharma_dock_polished_out.sdf, "
      "pharma_dock_final_out.sdf, pharma_dock_top5_diverse_out.sdf")

# 5. PyMOL visualizer
pml_content = f"""# PyMOL Script for Pharmacophore-Restraint Docking Comparison (PDB 9Z1L)
reinitialize
load receptor.mol2, kit_receptor
load a1czz_crystal_pose.sdf, reference_crystal_pose
load pharma_dock_free_out.sdf, free_docked
load pharma_dock_restrained_out.sdf, restrained_docked
load pharma_dock_final_out.sdf, final_docked
load pharma_dock_top5_diverse_out.sdf, top5_diverse

hide everything, kit_receptor
show cartoon, kit_receptor
color wheat, kit_receptor

hide everything, reference_crystal_pose
show sticks, reference_crystal_pose
color green, reference_crystal_pose

hide everything, free_docked
show sticks, free_docked
color red, free_docked
set stick_radius, 0.18, free_docked

hide everything, restrained_docked
show sticks, restrained_docked
color orange, restrained_docked
set stick_radius, 0.20, restrained_docked

hide everything, final_docked
show sticks, final_docked
color cyan, final_docked
set stick_radius, 0.24, final_docked

hide everything, top5_diverse
show sticks, top5_diverse
util.cbaw top5_diverse
set stick_radius, 0.16, top5_diverse
set all_states, on, top5_diverse

zoom reference_crystal_pose, 8.0

print "================================================================="
print "  Green: crystal reference | Red: free-docked (no restraints)"
print "  Orange: restrained SA only | Cyan: final (restrained + polish + fine refine)"
print "  White/multi: top5_diverse -- all 5 diverse final candidates shown at once"
print "  (all_states on: every candidate visible simultaneously, not as movie frames)"
print "================================================================="
"""
(DEMO_DIR / "visualize_pharmacophore_pymol.pml").write_text(pml_content)
print(f"[✓] PyMOL visualization script written: {DEMO_DIR / 'visualize_pharmacophore_pymol.pml'}")
