"""
Pharmacophore-Restraint-Guided Docking on PDB 9Z1L (KIT V654A + BLU-654/A1CZZ).

Compares Simulated Annealing docking WITH vs WITHOUT the pharmacophore
restraints in pharma.restr (3 aromatic-ring centroids + the 2 aniline N-H
hinge-binding donors, generated by make_pharma_restr.py from the crystal
pose) -- demonstrating how pharmacophore guidance steers the search back
toward the pharmacologically relevant binding mode.
"""
from pathlib import Path
import numpy as np
from rdkit import Chem
from rdkit.Chem import rdMolAlign

from openmm_dock.cavity import CavityDefinition
from openmm_dock.engine import DockingEngine
from openmm_dock.core import SDFParser

DEMO_DIR = Path(__file__).resolve().parent

print("=" * 95)
print("   OPENMM-DOCK: PHARMACOPHORE-RESTRAINT-GUIDED DOCKING (PDB 9Z1L: KIT V654A + BLU-654)")
print("=" * 95)

cavity = CavityDefinition.from_prm_file(DEMO_DIR / "cavity.prm")
xtal_mol = SDFParser.load_molecules(DEMO_DIR / "a1czz_crystal_pose.sdf")[0]
xtal_coords = xtal_mol.GetConformer().GetPositions()


def rmsd_to_xtal(mol: Chem.Mol) -> float:
    coords = mol.GetConformer().GetPositions()
    return float(np.sqrt(np.mean(np.sum((coords - xtal_coords) ** 2, axis=1))))


# 1. WITHOUT pharmacophore restraints (physical scoring only)
print("\n[1] Simulated Annealing docking WITHOUT pharmacophore restraints...")
engine_free = DockingEngine(receptor_path=DEMO_DIR / "receptor.mol2", cavity=cavity)
free_results = engine_free.dock_simulated_annealing(xtal_mol, n_runs=10, anneal_steps=10, steps_per_temp=100)
free_results.sort(key=lambda r: r.score)
for rank, r in enumerate(free_results):
    print(f"  Free Rank #{rank + 1}: Score = {r.score:.3f} | RMSD to Xtal = {rmsd_to_xtal(r.mol):.2f} Å")

# 2. WITH pharmacophore restraints
print("\n[2] Simulated Annealing docking WITH pharmacophore restraints (pharma.restr)...")
engine_pharma = DockingEngine(
    receptor_path=DEMO_DIR / "receptor.mol2", cavity=cavity, pharma_restr_path=DEMO_DIR / "pharma.restr"
)
pharma_results = engine_pharma.dock_simulated_annealing(xtal_mol, n_runs=10, anneal_steps=10, steps_per_temp=100)
pharma_results.sort(key=lambda r: r.score)
for rank, r in enumerate(pharma_results):
    print(f"  Pharma Rank #{rank + 1}: Score = {r.score:.3f} (Restraint = {r.scores['SCORE.RESTR.PHARMA']:.2f}) | RMSD to Xtal = {rmsd_to_xtal(r.mol):.2f} Å")

best_free, best_pharma = free_results[0], pharma_results[0]
print("\n" + "=" * 80)
print("COMPARISON: Best Pose RMSD to Crystal")
print(f"  Without restraints : {rmsd_to_xtal(best_free.mol):.2f} Å (Score {best_free.score:.2f})")
print(f"  With restraints     : {rmsd_to_xtal(best_pharma.mol):.2f} Å (Score {best_pharma.score:.2f}, "
      f"Restraint {best_pharma.scores['SCORE.RESTR.PHARMA']:.2f})")
print("=" * 80)

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_free_out.sdf"))
for r in free_results:
    w.write(r.mol)
w.close()

w = Chem.SDWriter(str(DEMO_DIR / "pharma_dock_restrained_out.sdf"))
for r in pharma_results:
    w.write(r.mol)
w.close()
print("\n[✓] Saved pharma_dock_free_out.sdf and pharma_dock_restrained_out.sdf")

# 3. PyMOL visualizer
pml_content = f"""# PyMOL Script for Pharmacophore-Restraint Docking Comparison (PDB 9Z1L)
reinitialize
load receptor.mol2, kit_receptor
load a1czz_crystal_pose.sdf, reference_crystal_pose
load pharma_dock_free_out.sdf, free_docked
load pharma_dock_restrained_out.sdf, restrained_docked

hide everything, kit_receptor
show cartoon, kit_receptor
color wheat, kit_receptor

hide everything, reference_crystal_pose
show sticks, reference_crystal_pose
color green, reference_crystal_pose

hide everything, free_docked
show sticks, free_docked
color red, free_docked
set stick_radius, 0.18, free_docked

hide everything, restrained_docked
show sticks, restrained_docked
color cyan, restrained_docked
set stick_radius, 0.22, restrained_docked

pseudoatom pharma_pt1, pos=[{pharma_results[0].mol.GetConformer().GetPositions()[0][0]:.2f}, {pharma_results[0].mol.GetConformer().GetPositions()[0][1]:.2f}, {pharma_results[0].mol.GetConformer().GetPositions()[0][2]:.2f}]

zoom reference_crystal_pose, 8.0

print "================================================================="
print "  Green: crystal reference | Red: free-docked (no restraints)"
print "  Cyan:  pharmacophore-restrained docking"
print "================================================================="
"""
(DEMO_DIR / "visualize_pharmacophore_pymol.pml").write_text(pml_content)
print(f"[✓] PyMOL visualization script written: {DEMO_DIR / 'visualize_pharmacophore_pymol.pml'}")
